### ISSUE TITLE
Handle blank subjects

### ISSUE THREAD

**Issue by Deven1902** [Deven1902/MailSensei#2]
Emails with blank subjects are not getting handled and rendered properly. 

the subject is surely showing a blank subject line... but the tags are generating some random blabber.

**Comment by Atharv-Nalwade** [comment]
I have modified the code to render "No Subject" in case no subject is provided. The gibberish tag generation for such is yet to be handled
Kindly review my #1 and I will make PR of the above changes then .

**Comment by Atharv-Nalwade** [comment]
PR #3  addresses blank subject handling issues.

**Comment by asyncdoggo** [comment]
fixed in ad15e61 with #3
